a

diff --git a/test1/deployments/deploy.yaml b/test1/deployments/deploy.yaml
--- a/test1/deployments/deploy.yaml
+++ b/test1/deployments/deploy.yaml
@@ -1,7 +1,7 @@
 apiVersion: apps/v1
 kind: Deployment
 metadata:
-  name: failing-app
+  name: failing-app-1
   labels:
     app: failure-test
 spec:
@@ -29,3 +29,35 @@ spec:
       
       # Optional: Controls how quickly Kubernetes tries to restart the failing pod
       restartPolicy: Always
+---
+apiVersion: apps/v1
+kind: Deployment
+metadata:
+  name: failing-app-2
+  labels:
+    app: failure-test
+spec:
+  replicas: 1
+  selector:
+    matchLabels:
+      app: failure-test
+  template:
+    metadata:
+      labels:
+        app: failure-test
+    spec:
+      containers:
+      - name: busybox-script
+        image: busybox:latest
+        # The 'command' field overrides the ENTRYPOINT
+        # The 'args' field provides arguments to that command
+        command: ["/bin/sh", "-c"]
+        args:
+          - |
+            echo "Starting script..."
+            sleep 3
+            echo "Crashing now with exit code 1"
+            exit 1
+      
+      # Optional: Controls how quickly Kubernetes tries to restart the failing pod
+      restartPolicy: Always      
